### ISSUE TITLE
Two-factor auth support

### ISSUE THREAD

**Issue by dakotahp** [dschanoeh/hover-ddns#4]
Does this support logging in with two-factor authentication? I looked at the Hover functions and didn't see anything related to it. When I tried it out with the config file filled out it just hangs for me which might point to an inability to log into my account due to 2FA.

**Comment by dschanoeh** [comment]
I don't know how login with 2FA works at Hover and tbh it would defeat the purpose here since hover-ddns is designed to run headless and automatically update without human intervention.
If you come across a way to have this here work (e.g. with a special machine token) while still activating 2FA, we could try to implement that. I doubt that exists, though, since the whole API seems to be unofficial.

**Comment by dakotahp** [comment]
Yeah, true. I wasn't sure if I was missing something. It _may_ be possible to use the 1password-cli, for example, to extract a TOTP headless but that is probably a stretch. Particularly for an unofficial API. 

Thanks
